assertThrows("EvalException", (for a in [1, 2] {}))